name: Wanso
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  intl: ^0.20.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/banner_education2.jpg
      - assets/images/logo.png
      - assets/images/greetings.png
      - assets/images/numbers.png
      - assets/images/colors.png
      - assets/images/human_body.png
      - assets/images/colors.png
      - assets/images/water.png
      - assets/images/numbers.png
      - assets/images/conversation.png
      - assets/images/grammar_rules_-_intermediate_level.png
      - assets/images/app_icon.png
      - assets/images/cultural_context_-_intermediate_level.png
      - assets/images/grammar_rules_-_intermediate_level.png
      - assets/images/number_1.png
      - assets/images/number_2.png
      - assets/images/number_3.png
      - assets/images/number_4.png
      - assets/images/human_arm.png
      - assets/images/human_body.png
      - assets/images/human_foot.png
      - assets/images/human_hand.png
      - assets/images/human_head.png
      - assets/images/human_leg.png
      - assets/images/human_torso.png
      - assets/videos/greetings.mp4
      - assets/videos/numbers.mp4
      - assets/videos/colors.mp4
      - assets/images/video_demo.png
      - assets/images/guide.png
      - assets/images/learn.png

      - assets/audio/
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
